acronyms_list = [(r'\bMRI\b', 'magnetic resonance image'),
            (r'\bCT\b', 'computed tomography'),
            (r'\bPET\b', 'positron emission tomography'),
            (r'\bSPECT\b', 'single photon emission computed tomography'),
            (r'\bUS\b', 'ultrasound'),
            (r'\bALS\b', 'amyotrophic lateral sclerosis'),
            (r'\bECG\b', 'electrocardiogram'),
            (r'\bEKG\b', 'electrocardiogram'),
            (r'\bEEG\b', 'electroencephalogram'),
            (r'\bEMG\b', 'electromyogram'),
            (r'\bHR\b', 'heart rate'),
            (r'\bABX\b', 'antibiotics'),
            (r'\bAF\b', 'atrial fibrillation'),
            (r'\bXR\b', 'x ray'),
            (r'\bBLS\b', 'basic life support'),
            (r'\bBMD\b', 'bone mass density'),
            (r'\bBMI\b', 'body mass index'),
            (r'\bBP\b', 'blood pressure'),
            (r'\bBx\b', 'biopsy'),
            (r'\bCAD\b', 'coronary artery disease'),
            (r'\bCAT\b', 'computed axial tomography'),
            (r'\bCBF\b', 'cerebral blood flow'),
            (r'\bCO2\b', 'carbon dioxide'),
            (r'\bO2\b', 'oxygen'),
            (r'\bH2O\b', 'water'),
            (r'\bCV\b', 'cardiovascular'),
            (r'\bDNA\b', 'deoxyribonucleic acid'),
            (r'\bRNA\b', 'ribonucleic acid'),
            (r'\bDx\b', 'diagnosis'),
            (r'\bEOC\b', 'emergency operations center'),
            (r'\bFX\b', 'fracture'),
            (r'\bGI\b', 'gastrointestinal'),
            (r'\bGP\b', 'general practitioner'),
            (r'\bICU\b', 'intensive care unit'),
            (r'\bIQ\b', 'intelligence quotient'),
            (r'\bIT\b', 'information technology'),
            (r'\bIV\b', 'intravenous'),
            (r'\bLOF\b', 'loss of fluid'),
            (r'\bLTC\b', 'long term care'),
            (r'\bLV\b', 'left ventricle'),
            (r'\bRV\b', 'right ventricle'),
            (r'\bMG\b', 'milligram'),
            (r'\bML\b', 'milliliter'),
            (r'\bNIH\b', 'national institutes of health'),
            (r'\bNM\b', 'neuromuscular'),
            (r'\bOCD\b', 'obsessive compulsive disorder'),
            (r'\bOT\b', 'occupational therapy'),
            (r'\bPHS\b', 'public health service'),
            (r'\bPPE\b', 'personal protective equipment'),
            (r'\bQA\b', 'quality assurance'),
            (r'\bQI\b', 'quality improvement'),
            (r'\bRF\b', 'risk factor'),
            (r'\bRx\b', 'treatment'),
            (r'\bSSA\b', 'social security administration'),
            (r'\bTB\b', 'tuberculosis'),
            (r'\bTLC\b', 'total lung capacity'),
            (r'\bVF\b', 'ventricular fibrillation'),
            (r'\bWHO\b', 'world health organization')]